import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import image1 from "../public/images/who-we-are.png";
import image2 from "../public/images/how-we-work.png";
import arrow_right from "../public/images/arrow-right.svg";

export default function AboutUs() {
  return (
    <div>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header
        style={{
          backgroundImage: "url('/images/about-header.png')",
          backgroundPosition: "center",
          backgroundSize: "cover",
        }}
      >
        <div className="header-text-body">
          <div>
            <h1>ABOUT US</h1>
            <p>
              At Determinas, we use advanced technologies in Artificial
              Intelligence (AI), Innovation, and operations research to help
              organisations implement data-driven digital transformations that
              involve all aspects of their business.
            </p>
          </div>
        </div>
      </header>
      <section
        style={{
          padding: "1rem 3rem",
        }}
      >
        <div>
          <h2>WHO WE ARE</h2>
          <p>
            We are Africa’s foremost AI-driven company. We help organizations
            implement data-driven digital strategy that touches all aspects of
            their business using advanced data analytics techniques such as
            machine learning, deep learning and artificial intelligence.
          </p>
        </div>
        <div className="choose-us">
          <Image src={image1} />
          <div>
            <h3>WHY YOU SHOULD CHOOSE DETERMINAS ?</h3>
            <p>
              In everything we do, Determinas strives for operational excellence
              and exceptional perfomance. We believe in Speed and Accurate
              Insight - that using intelligence, expertise, and science to
              improve businesses can help create a better and more prosperous
              society for everyone.{" "}
            </p>
          </div>
        </div>
        <div className="mission-vision">
          <div>
            <h3>OUR MISSION</h3>
            <ul>
              <li>
                To help organisations implement data-driven digital startegies
                using advanced data analytics techniques.
              </li>
              <li>
                To help inntegrate AI and Data solutions into businesses to
                acheive competitive advantage, increase their revenue and
                optimize their processes.
              </li>
              <li>
                To help businesses leverage the full potential of technology and
                Big Data.
              </li>
            </ul>
          </div>
          <div>
            <h3>OUR VISION</h3>
            <p>Bridging the gap between businesses and AI</p>
          </div>
        </div>
        <div className="how-we-work">
          <Image src={image2} />
          <div>
            <h3>HOW WE WORK</h3>
            <p>
              We use data to keep you ahead of your competitors by helping your
              organisation make data-driven business decisions. We help your
              business harness to full potential, the opportunities in
              technology and Big Data.
            </p>
            <button>
              <Image src={arrow_right} />
              LET’S DISCUSS YOUR PROJECT
            </button>
          </div>
        </div>
      </section>
      <section className="core-values"></section>
    </div>
  );
}
