import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import search from "../public/images/search.svg";
import arrow_right from "../public/images/arrow-right.svg";
import feature1 from "../public/images/feature-1.png";
import feature2 from "../public/images/feature-2.png";
import feature3 from "../public/images/feature-3.png";
import feature4 from "../public/images/feature-4.png";
import feature5 from "../public/images/feature-5.png";
import feature6 from "../public/images/feature-6.png";

export default function Blog() {
  const topics = [
    "ALL",
    "TELECOMMUNICATIONS",
    "MANUFACTURING",
    "MARKET RESEARCH",
    "PRODUCT DESIGN",
    "DATA SCIENCE",
  ];
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header
        style={{
          backgroundImage: "url('/images/blog-header.png')",
          backgroundPosition: "center",
          backgroundSize: "cover",
        }}
      >
        <div className="header-text-body">
          <div>
            <h1>BLOG</h1>
            <p>
              We love to share our insights on the latest in digital
              transformation. Read our blog.
            </p>
          </div>
        </div>
      </header>
      <section className="blog-search">
        <div className="input-div">
          <input placeholder="Search for a Topic..." />
          <button>
            <Image src={search} />
          </button>
        </div>
        <div>
          <p>SUBSCRIBE TO OUR NEWSLETTER</p>
          <div className="input-div">
            <input placeholder="Enter an E-mail Address..." />
            <button>
              <Image src={arrow_right} />
            </button>
          </div>
        </div>
      </section>
      <section
        style={{
          padding: "1rem 3rem",
        }}
      >
        <div>
          <h2>TOPICS</h2>
          <div className="topics">
            {topics.map((topic, i) => (
              <p key={i} className={i == 0 && "active"}>
                {topic}
              </p>
            ))}
          </div>
        </div>
        <div>
          <div className="features">
            <div>
              <Image src={feature1} />
              <div className="text">
                <h5>Model Fitting and Generalization</h5>
                <p>Machine Learning</p>
              </div>
            </div>
            <div>
              <Image src={feature2} />
              <div className="text">
                <h5>What is Artificial Intelligence?</h5>
                <p>Artificial Intelligence</p>
              </div>
            </div>
            <div>
              <Image src={feature3} />
              <div className="text">
                <h5>Artificial Intelligence in the Health Care Sector</h5>
                <p>Healthcare</p>
              </div>
            </div>
          </div>
          <div className="features">
            <div>
              <Image src={feature4} />
              <div className="text">
                <h5>Model Fitting and Generalization</h5>
                <p>Machine Learning</p>
              </div>
            </div>
            <div>
              <Image src={feature5} />
              <div className="text">
                <h5>What is Artificial Intelligence?</h5>
                <p>Artificial Intelligence</p>
              </div>
            </div>
            <div>
              <Image src={feature6} />
              <div className="text">
                <h5>Artificial Intelligence in the Health Care Sector</h5>
                <p>Healthcare</p>
              </div>
            </div>
          </div>
          <div className="pagination">
            <span className="active">1</span>
            <span>2</span>
            <span>3</span>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
}
