import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import explore1 from "../public/images/explore-1.png";
import explore2 from "../public/images/explore-2.png";
import explore3 from "../public/images/explore-3.png";
import explore4 from "../public/images/explore-4.png";
import explore5 from "../public/images/explore-5.png";
import explore6 from "../public/images/explore-6.png";

export default function CaseStudies() {
  return (
    <div>
      <Head>
        <title>Case Studies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header
        style={{
          backgroundImage: "url('/images/case-studies-header.png')",
          backgroundPosition: "center",
          backgroundSize: "cover",
        }}
      >
        <div className="blur-bg"></div>
        <div className="header-text-body">
          <div>
            <h1>CASE STUDIES</h1>
            <p>
              We partner with innovative companies like yours at every stage,
              helping them accelerate their growth and achieve their unique
              goals. Explore our rich collection of Case studies created by
              experts at Determinas.
            </p>
          </div>
        </div>
      </header>
      <section className="container-section case-studies">
        <div>
          <div className="explore">
            <div className="item">
              <Image src={explore1} alt="" />
              <div className="text">
                <h5>Lorem Ipsum Dolor Sit Amet</h5>
                <p>Telecommunications</p>
              </div>
            </div>
            <div className="item">
              <Image src={explore2} alt="" />
              <div className="text">
                <h5>Lorem Ipsum Dolor Sit Amet</h5>
                <p>Banking and Finance</p>
              </div>
            </div>
            <div className="item">
              <Image src={explore3} alt="" />
              <div className="text">
                <h5>Lorem Ipsum Dolor Sit Amet</h5>
                <p>Education</p>
              </div>
            </div>
          </div>
          <div className="explore">
            <div className="item">
              <Image src={explore4} alt="" />
              <div className="text">
                <h5>Lorem Ipsum Dolor Sit Amet</h5>
                <p>Telecommunications</p>
              </div>
            </div>
            <div className="item">
              <Image src={explore5} alt="" />
              <div className="text">
                <h5>Lorem Ipsum Dolor Sit Amet</h5>
                <p>Banking and Finance</p>
              </div>
            </div>
            <div className="item">
              <Image src={explore6} alt="" />
              <div className="text">
                <h5>Lorem Ipsum Dolor Sit Amet</h5>
                <p>Education</p>
              </div>
            </div>
          </div>
        </div>
        <div className="pagination">
          <span className="active">1</span>
          <span>2</span>
          <span>3</span>
        </div>
      </section>
      <Footer />
    </div>
  );
}
