import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";
import Industries from "../components/Indutries";
import TalentPool from "../components/Talent Pool";
import styles from "../styles/Home.module.css";
import arrow from "../public/images/arrow.svg";
import explore1 from "../public/images/explore-1.png";
import explore2 from "../public/images/explore-2.png";
import explore3 from "../public/images/explore-3.png";
import feature1 from "../public/images/feature-1.png";
import feature2 from "../public/images/feature-2.png";
import feature3 from "../public/images/feature-3.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Determinas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header>
        <div className="header-text-body">
          <div>
            <h1>DIGITAL TRANSFORMATION</h1>
            <p>
              Harness the power of new, fast, and ever-evolving digital
              technology to solve your business challenges
            </p>
            <button>CONTACT US TODAY</button>
          </div>
        </div>
      </header>
      <section>
        <div
          style={{
            padding: "1rem",
          }}
        >
          <h2>DISCOVER</h2>
          <p>
            How Our Bespoke & Contextual Research, Analytics, and Technology
            Solutions Can Empower Your Crucial Business Decisions
          </p>
        </div>

        <div className="discover">
          <div className="item">
            <h4> BIG DATA AND ANALYTICS</h4>
            <ul>
              <li>Data Governance</li>
              <li>Data Engineering</li>
              <li>Business intelligence & Data Visualisation</li>
              <li>Data Science</li>
              <Image src={arrow} alt="" />
            </ul>
          </div>
          <div className="item">
            <h4> SOFTWARE PRODUCT INNOVATION</h4>
            <ul>
              <li>End to End Product Engineering</li>
              <li>Product Design</li>
              <li>Product Development</li>
              <li>App Restructuring</li>
              <Image src={arrow} alt="" />
            </ul>
          </div>
          <div className="item">
            <h4>TALENT MOBILITY</h4>
            <ul>
              <li>Talent Fellowship</li>
              <li>Talent As a Service</li>
              <li>Talent Outsourcing</li>
              <Image src={arrow} alt="" />
            </ul>
          </div>
          <div className="item">
            <h4> GROWTH MARKETING</h4>
            <ul>
              <li>Business Strategy Support</li>
              <li>Market Research</li>
              <li>Market Intelligence</li>
              <li>Investment Research </li>
              <Image src={arrow} alt="" />
            </ul>
          </div>
        </div>
      </section>
      <section className="container-section">
        <div>
          <h2>OUR FOCUS INDUSTRIES</h2>
          <p>
            Our in-depth experience with industries helps us understand the
            market specifics and create software solutions customized to a
            specific niche. Our goal is to help your business exceed customers’
            expectations and to help you take a leading role in your industry.
          </p>
        </div>
        <Industries />
      </section>
      <section className="container-section">
        <div>
          <h2>EXPLORE</h2>
          <p>
            Our rich collection of case studies created by experts at Determinas
          </p>
        </div>
        <div className="explore">
          <div className="item">
            <Image src={explore1} alt="" />
            <div className="text">
              <h5>Lorem Ipsum Dolor Sit Amet</h5>
              <p>Telecommunications</p>
            </div>
          </div>
          <div className="item">
            <Image src={explore2} alt="" />
            <div className="text">
              <h5>Lorem Ipsum Dolor Sit Amet</h5>
              <p>Banking and Finance</p>
            </div>
          </div>
          <div className="item">
            <Image src={explore3} alt="" />
            <div className="text">
              <h5>Lorem Ipsum Dolor Sit Amet</h5>
              <p>Education</p>
            </div>
          </div>
        </div>
      </section>
      <section className="container-section">
        <div>
          <h2>FEATURED CONTENT</h2>
        </div>
        <div className="features">
          <div>
            <Image src={feature1} alt="" />
            <div className="text">
              <h5>Model Fitting and Generalization</h5>
              <p>Machine Learning</p>
            </div>
          </div>
          <div>
            <Image src={feature2} alt="" />
            <div className="text">
              <h5>What is Artificial Intelligence?</h5>
              <p>Artificial Intelligence</p>
            </div>
          </div>
          <div>
            <Image src={feature3} alt="" />
            <div className="text">
              <h5>Artificial Intelligence in the Health Care Sector</h5>
              <p>Healthcare</p>
            </div>
          </div>
        </div>
      </section>
      <TalentPool />
      <Footer />
    </div>
  );
}
