import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/Navigation";
import styles from "../styles/Home.module.css";
import arrow from "../public/images/arrow.svg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header>
        <div className="header-text-body">
          <h1>DIGITAL TRANSFORMATION</h1>
          <p>
            Harness the power of new, fast, and ever-evolving digital technology
            to solve your business challenges
          </p>
          <button>CONTACT US TODAY</button>
        </div>
      </header>
      <section>
        <div
          style={{
            padding: "1rem",
          }}
        >
          <h2>DISCOVER</h2>
          <p>
            How Our Bespoke & Contextual Research, Analytics, and Technology
            Solutions Can Empower Your Crucial Business Decisions
          </p>
        </div>

        <div className="discover">
          <div className="item">
            <h4> BIG DATA AND ANALYTICS</h4>
            <ul>
              <li>Data Governance</li>
              <li>Data Engineering</li>
              <li>Business intelligence & Data Visualisation</li>
              <li>Data Science</li>
              <Image src={arrow} />
            </ul>
          </div>
          <div className="item">
            <h4> SOFTWARE PRODUCT INNOVATION</h4>
            <ul>
              <li>End to End Product Engineering</li>
              <li>Product Design</li>
              <li>Product Development</li>
              <li>App Restructuring</li>
              <Image src={arrow} />
            </ul>
          </div>
          <div className="item">
            <h4>TALENT MOBILITY</h4>
            <ul>
              <li>Talent Fellowship</li>
              <li>Talent As a Service</li>
              <li>Talent Outsourcing</li>
              <Image src={arrow} />
            </ul>
          </div>
          <div className="item">
            <h4> GROWTH MARKETING</h4>
            <ul>
              <li>Business Strategy Support</li>
              <li>Market Research</li>
              <li>Market Intelligence</li>
              <li>Investment Research </li>
              <Image src={arrow} />
            </ul>
          </div>
        </div>
      </section>
      <section>
        <div
          style={{
            padding: "1rem",
          }}
        >
          <h2>OUR FOCUS INDUSTRIES</h2>
          <p>
            Our in-depth experience with industries helps us understand the
            market specifics and create software solutions customized to a
            specific niche. Our goal is to help your business exceed customers’
            expectations and to help you take a leading role in your industry.
          </p>
        </div>
      </section>
    </div>
  );
}
