import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";

export default function Indutsries() {
  return (
    <div>
      <Head>
        <title>Industries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header
        style={{
          backgroundImage: "url('/images/industries-header.png')",
          backgroundPosition: "center",
          backgroundSize: "cover",
        }}
      >
        <div className="header-text-body">
          <div>
            <h1>INDUSTRIES WE SERVE</h1>
            <p>
              We combine technology with industry expertise. Innovate your niche
              with custom software tailored to your specific business needs.
            </p>
          </div>
        </div>
      </header>
      <section>
        <div
          style={{
            padding: "1rem",
          }}
        >
          <p>
            Our experience with industries helps us understand the market
            specifics and create software customized to a specific niche. Our
            goal is to help businesses exceed customers’ expectations to become
            a market leader in the industry.
          </p>
          <h2>INDUSTRIES WE SERVE</h2>
        </div>
      </section>
      <Footer />
    </div>
  );
}
