import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import growth from "../public/images/growth.svg";
import analytics from "../public/images/analytics.svg";
import computer from "../public/images/computer.svg";
import bulb from "../public/images/bulb.svg";

export default function Service() {
  return (
    <div>
      <Head>
        <title>Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header
        style={{
          backgroundImage: "url('/images/service-header.png')",
          backgroundPosition: "center",
          backgroundSize: "cover",
        }}
      >
        <div className="header-text-body">
          <h1>SERVICES WE OFFER</h1>
          <p>
            Triumph new business milestones as we super-charge your growth with
            our full-cycle software solutions, innovation and development.
          </p>
          <button>CONTACT US TODAY</button>
        </div>
      </header>
      <section>
        <div
          style={{
            padding: "1rem",
          }}
        >
          <p>
            Get proven software engineering and consulting services. We partner
            with companies like yours to create custom solutions that drive
            business success.
          </p>
          <h2>WHAT WE OFFER</h2>
        </div>
        <div className="services">
          <div>
            <div className="service-img">
              <Image src={analytics} />
            </div>

            <div className="item">
              <h4>BIG DATA AND ANALYTICS</h4>
              <ul>
                <li>Data Governance</li>
                <li>Data Engineering</li>
                <li>Business Intelligence and Data Visualisation</li>
                <li>Data Science </li>
              </ul>
            </div>
          </div>
          <div>
            <div className="service-img">
              <Image src={computer} />
            </div>

            <div className="item">
              <h4>SOFTWARE PRODUCT INNOVATION</h4>
              <ul>
                <li>End to End Product Engineering</li>
                <li>Product Design</li>
                <li>Product Development</li>
                <li>App Restructuring </li>
              </ul>
            </div>
          </div>
          <div>
            <div className="service-img">
              <Image src={bulb} />
            </div>

            <div className="item">
              <h4>TALENT MOBILITY</h4>
              <ul>
                <li>Talent Fellowship</li>
                <li>Talent As a Service</li>
                <li>Talent Outsourcing</li>
              </ul>
            </div>
          </div>
          <div>
            <div className="service-img">
              <Image src={growth} />
            </div>

            <div className="item">
              <h4> GROWTH MARKETING</h4>
              <ul>
                <li>Business Strategy Support</li>
                <li>Market Research</li>
                <li>Market Intelligence</li>
                <li>Investment Research </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className="talent-pool">
        <p>NEED TO PUT TOGETHER A TEAM OF TALENTS FOR YOUR NEXT PROJECT?</p>
        <button>ACCESS OUR TALENT POOL</button>
      </section>
      <Footer />
    </div>
  );
}
