import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import WhatWeOffer from "../components/What we Offer";
import TalentPool from "../components/Talent Pool";

export default function Services() {
  return (
    <div>
      <Head>
        <title>Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header
        style={{
          backgroundImage: "url('/images/service-header.png')",
          backgroundPosition: "center",
          backgroundSize: "cover",
        }}
      >
        <div className="overlay"></div>
        <div className="blur-bg"></div>
        <div className="header-text-body">
          <div>
            <span>Home/</span>
            <h1>SERVICES WE OFFER</h1>
            <p>
              Triumph new business milestones as we super-charge your growth
              with our full-cycle software solutions, innovation and
              development.
            </p>
            <button>
              {" "}
              <Link href="/contact-us">CONTACT US TODAY</Link>
            </button>
          </div>
        </div>
      </header>
      <section className="container-section">
        <div>
          <p>
            Get proven software engineering and consulting services. We partner
            with companies like yours to create custom solutions that drive
            business success.
          </p>
          <h2>WHAT WE OFFER</h2>
        </div>
        <WhatWeOffer />
      </section>
      <TalentPool />
      <Footer />
    </div>
  );
}
